### ISSUE TITLE
Sending tab to a firefox instance

### ISSUE THREAD

**Issue by shalak** [Mikescher/firefox-sync-client#11]
Is there a way to trigger a "Send link to Device" feature using this client? From what I see it can only list already opened tabs, but maybe I am missing something...

**Comment by Mikescher** [comment]
Hmm as far as I know the send-tab-to-device feature has nothing to do with firefox-sync.  
(You can read about the available API [here](https://mozilla-services.readthedocs.io/en/latest/sync/index.html) and [here](https://mozilla-services.readthedocs.io/en/latest/storage/apis-1.5.html).

If you find an API you can probably spin up a small bash script, but I think it's out-of-scope for this project

**Comment by orangepizza** [comment]
for record on firefox side send tab is handled in https://github.com/mozilla/gecko-dev/blob/ed2b06f15a5081b2b5e4ab101184c1272d249235/services/fxaccounts/FxAccountsCommands.sys.mjs
and open/close remote tap API uses identity.mozilla.com/cmd/ as prefix, but firefox sends request with same oauth scope key as sync use, idendty.mozilla.com/apps/oldsync .
