### ISSUE TITLE
Linux installation with homebrew

### ISSUE THREAD

**Issue by lamyergeier** [Mikescher/firefox-sync-client#12]
I installed on Fedora 39 using:

- [[Homebrew](https://formulae.brew.sh/formula/ffsclient)](https://formulae.brew.sh/formula/ffsclient): `brew tap Mikescher/tap && brew install ffsclient`

But, I am getting the error `bash: /home/linuxbrew/.linuxbrew/bin/ffsclient: Permission denied` when I try to login.

Also ,

```
file  /home/linuxbrew/.linuxbrew/Cellar/ffsclient/64/bin/ffsclient 
/home/linuxbrew/.linuxbrew/Cellar/ffsclient/64/bin/ffsclient: Mach-O 64-bit x86_64 executable
```

does this mean that homebrew installation is not applicable for linux! I am confused due to Mach-O in above output!

Please support homebrew for linux as homebrew supports linux.

**Comment by Mikescher** [comment]
yeah, homebrew is currently only the mac binary see [homebrew.sh](https://github.com/Mikescher/firefox-sync-client/blob/master/_data/package-data/homebrew.sh).

On linux you can use the compiled binaries directly, the *.deb package or the AUR.

But you can make a PR to change the homebrew script to support linux, personally I don't use homebrew and don't have a machine to test it on.  
(I guess you would have to instruct homebrew somehow to install the correct binaries on the correct architectures?)
