### ISSUE TITLE
Firefox Accounts API Changes

### ISSUE THREAD

**Issue by Mikescher** [Mikescher/firefox-sync-client#13]
Since 2024-05-15 login is no longer possible:

```
Start HTTP call to https://api.accounts.firefox.com/v1/certificate/sign [[ try 1 ]]
HTTP call returned Statuscode 404
Request returned statuscode 404
Request returned Header [X-Frame-Options] := 'DENY'
Request returned Header [X-Content-Type-Options] := 'nosniff'
Request returned Header [Cache-Control] := 'no-cache'
Request returned Header [Content-Type] := 'application/json; charset=utf-8'
Request returned Header [Content-Length] := '170'
Request returned Header [Vary] := 'origin'
Request returned Header [X-Xss-Protection] := '1; mode=block'
Request returned Header [X-Download-Options] := 'noopen'
Request returned Header [Via] := '1.1 google'
Request returned Header [Timestamp] := '1715881250'
Request returned Header [Strict-Transport-Security] := 'max-age=31536000; includeSubDomains'
Request returned Header [Alt-Svc] := 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'
Request returned Header [Server] := 'nginx'
Request returned Header [Date] := 'Thu, 16 May 2024 17:40:50 GMT'
Request returned body:
{"code":404,"errno":116,"error":"Gone","message":"This endpoint is no longer supported","info":"https://mozilla.github.io/ecosystem-platform/api#section/Response-format"}
failed to refresh session, cause: failed to assert BID, cause: Failed to sign cert, cause: Request failed, cause: ffsync.http_404: call to https://api.accounts.firefox.com/v1/certificate/sign returned statuscode 404
```
 
Probably need to implement the new api:

 - https://mozilla.github.io/ecosystem-platform/api#section/Response-format
 - https://mozilla.github.io/ecosystem-platform/api
 - https://wiki.mozilla.org/Identity/AttachedServices/KeyServerProtocol

**Comment by Mikescher** [comment]
Fixed by v1.7

**Comment by zeorin** [comment]
I'm having issues logging in.

I have 2 email addresses attached to my Firefox Account, zeorin@gmail.com and me@xandor.co.za. The first was the email address I initially created the account with and the second is the one I later changed the account's primary email address to. The first was then changed to be the recovery email address.

I also have 2FA enabled.

When trying to log in with `ffsclient login me@xandor.co.za password123 --device-name ffsclient --otp 123456`, I get the following error:

```
common.internal_error: call to /login returned statuscode 400
Body:
{"code":400,"errno":120,"error":"Bad Request","message":"Incorrect email case","info":"https://mozilla.github.io/ecosystem-platform/api#section/Response-format","email":"zeorin@gmail.com"}
```

I then swapped the email address roles around (i.e. made zeorin@gmail.com the primary email address again), and tried again with `ffsclient login zeorin@gmail.com password123 --device-name ffsclient --otp 123456`, which gave me this error:

```
failed to read response-body request, cause: stream error: stream ID 3; PROTOCOL_ERROR; received from peer
```

**Comment by Mikescher** [comment]
Hmm, I don't think this has anything to do with this ticket.

Can you create a new issue and I'll try to reproduce it when I find a bit of free time.  
The second error is highly suspicious - looks like the raw http request somehow failed? - Can you retry that with `-v` to see which api request fails?
