### ISSUE TITLE
Bad request when logging in

### ISSUE THREAD

**Issue by zeorin** [Mikescher/firefox-sync-client#15]
I have 2 email addresses attached to my Firefox Account, zeorin@gmail.com and me@xandor.co.za. The first was the email address I initially created the account with and the second is the one I later changed the account's primary email address to. The first was then changed to be the recovery email address.

I also have 2FA enabled.

When trying to log in with `ffsclient login me@xandor.co.za password123 --device-name ffsclient --otp 123456`, I get the following error:

```
common.internal_error: call to /login returned statuscode 400
Body:
{"code":400,"errno":120,"error":"Bad Request","message":"Incorrect email case","info":"https://mozilla.github.io/ecosystem-platform/api#section/Response-format","email":"zeorin@gmail.com"}
```

I then swapped the email address roles around (i.e. made zeorin@gmail.com the primary email address again), and tried again with `ffsclient login zeorin@gmail.com password123 --device-name ffsclient --otp 123456`, which gave me this error:

```
failed to read response-body request, cause: stream error: stream ID 3; PROTOCOL_ERROR; received from peer
```

Will run it with `-v` in a bit.

_Originally posted by @zeorin in https://github.com/Mikescher/firefox-sync-client/issues/13#issuecomment-2185318013_

**Comment by zeorin** [comment]
I just tried it with `-v` and it worked! I literally fished the command I'd previously used out of my cli history and added `-v` at the end, and:

```
[... elided for brevity]

Save session to ~/.config/firefox-sync-client.secret
Session saved
Succesfully logged in
```

**Comment by Mikescher** [comment]
That is .... weird.   
`-v` does not do anything functional - it just logs all requests, transformations, intermediate values etc.

But if it works now - it's ok I guess ¯\\_(ツ)\_/¯
