### ISSUE TITLE
TSV output

### ISSUE THREAD

**Issue by peterjschroeder** [Mikescher/firefox-sync-client#2]
Would you consider adding an export option for tsv (Tab-separated values).

**Comment by Mikescher** [comment]
hmm shouldn't bee too hard to do,  
I'm currently (the next ~ 2 months) a bit busy (writing my thesis) - but after that I can look into it

But just out of interest: Whats your use case for that?

Also, in the meantime you can probably use the json output and pipe it into jq to convert it to tsv (or other formats....)

**Comment by peterjschroeder** [comment]
I can try to do it myself, if you will accept a commit for it. Go isn't really my language but I may be able to wing it.

I am piggybacking off your application to integrate sync into qutebrowser.

git@github.com:peterjschroeder/qb-scripts.git

I have it working by splitting strings, tsv would just be cleaner. Parsing json is a bit overkill for the info I need to capture. Tsv would also be useful for viewing your bookmarks in a spreadsheet.

**Comment by Mikescher** [comment]
> I can try to do it myself, if you will accept a commit for it. Go isn't really my language but I may be able to wing it.

Sure, feel free to give it a try.


You probably want to 

 - add a new OutputFormat in [formats.go](https://github.com/Mikescher/firefox-sync-client/blob/master/cli/formats.go)
 - implement the output for the subcommands you need (do not have to be all), eg in [cliBookmarksList.go](https://github.com/Mikescher/firefox-sync-client/blob/master/cli/impl/cliBookmarksList.go)
 - A good way would probably be a helper function similar to PrintPrimaryOutputTableExt(), that gets a `string[][]` array and prints a tsv, you can use "encoding/csv" from the go standardlibrary with `writer := csv.NewWriter(w); writer.Comma = '\t'` to print tsv (if you want you can also in the same way add csv output, should be the same just without the  `Comma = '\t'`)
 - update the --help output in [cliHelp.go](https://github.com/Mikescher/firefox-sync-client/blob/master/cli/impl/cliHelp.go)

Then just create a PR and I will look over it  👍

**Comment by peterjschroeder** [comment]
Thank you for the pointers.

Would it be preferable to add a seperator option to the existing Table code bypassing the padding and instead inserting the seperator?

**Comment by Mikescher** [comment]
> Would it be preferable to add a separator option to the existing Table code bypassing the padding and instead inserting the separator?

I would prefer it as a new method (but you can take the table code as a baseline), in the table output I tried to limit the printed column so that they would fit into a normal sized terminal, and I think the tsv/csv output should probably contain all information available.

**Comment by peterjschroeder** [comment]
Completed. I made a pull request.
