### ISSUE TITLE
login: `--device-name` and `--device-type` appear unimplemented

### ISSUE THREAD

**Issue by somasis** [Mikescher/firefox-sync-client#5]
Hi! Thanks for your project, I've been looking for a tool that could allow me to use Firefox Sync from the command line for a while.

I'm currently working on a script to synchronize my [qutebrowser](https://github.com/qutebrowser/qutebrowser) session using this tool, but I've run into an issue. It looks like `login` doesn't actually have `--device-name` and `--device-type` implemented, despite them appearing in `help`.

```text
somasis ~ ∴ ffsclient -v
1.4.0
somasis ~ ∴ ffsclient login "kylie@somas.is" "$(pass www/accounts.firefox.com/kylie@somas.is | head -n1)" --device-type "desktop" --device-name "somasis@ilo.somas.is:qutebrowser"
Unknown argument: device-type
```

**Comment by Mikescher** [comment]
Ah yeah you're right - fixed in 3c6f8eeeba4392dbaa511bdb88c4afcdef6539f3

If you get the latest release ( v1.5.0 ), it should be fixed.
