### ISSUE TITLE
Suggestion in case login fails with 404

### ISSUE THREAD

**Issue by cwdjankoski** [Mikescher/firefox-sync-client#6]
Hi and thanks for this super useful tool - I used to export all my bookmarks via the bookmarks panel and then parse the XML with R to keep a tabulated backup.  
This would simplify the process massively and the csv output is amazing - so thank you 🙇 

I am not sure if this would be helpful - but I found out that you need to be logged in to your Firefox account in the browser in order for the login to work. I kept getting this error until i realised that I am not logged in:  
```
API request failed, cause: Request failed, cause: ffsync.http_404: call to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/207392506/storage/crypto/keys returned statuscode 404
```

I just wanted to mention this - perhaps useful for some other people. Happy to add a comment to the README if you think this is useful (but maybe it's a rookie mistake, not sure so thought to ask)  

In any case, thanks again.

**Comment by Mikescher** [comment]
Hmm this is weird, I definitely did not need to be logged in in my browser.  

Sometimes mozilla will send you a confirmation mail, which you need to accept before the login works - but that's all.  
Perhaps this is a similar case, and once you log in via your browser the sync service server recognizes your ip and no longer needs an additional (mail) confirmation...

I'm currently a bit busy, but I will look into it when I have more time.

PS: if you want you can send me a PR with an updated README (perhaps add a FAQ section), I'm currently not at a computer, but can accept it from my phone :D
